package diamondcraftdevs.startups.speakingApp.const

object StringExtractor {
    const val RequestPermissionCode = 1
    val holderList = mutableListOf(
        "Flowers",
        "Fruits And Vegetables",
        "Internet",
        "Barbecue",
        "Crowded Place",
        "Mobile Apps",
        "History",
        "Laugh",
        "Weekends",
        "Number",
        "Magazine",
        "Hometown",
        "Sky",
        "newspaper",
        "Neighbor",
        "Work ",
        "study",
        "Dictionary",
        "Home/Accommodation",
        "Home Country",
        "Spending Time By Your Self",
        "Wallet",
        "Driving",
        "Transportations",
        "Window View",
        "Social Network",
        "Reading ",
        "Car Trip ",
        "Animals",
        "Pop Star",
        "Mirrors",
        "Break",
        "Relax ",
        "Physical Exercise",
        "Hair Cut",
        "Special Costumes",
        "Teenagers",
        "Area You Live In",
        "Watch",
        "Island",
        "Punctuality",
        "Mobile Phones",
        "Furniture",
        "Stage Of Life",
        "Primary School",
        "Math ",
        "TV And Radio",
        "Robots",
        "High School",
        "New Year",
        "Feel Happy",
        "Trees",
        "Decoration",
        "Farming",
        "Film",
        "Teacher",
        "Saving Money",
        "visitors",
        "Dream Job",
        "Bus or Taxi",
        "Language",
        "Home Country",
        "Festivals",
        "Emails",
        "Advertisements ",
        "Tea And Coffee",
        "Taking Rest",
        "Environmental Protection",
        "Politeness",
        "Sharing",
        "Gifts",
        "Wild animals",
        "Getting Up Early ",
        "Rainy Days",
        "Clothes And Fashion",
        "Noise",
        "Market",
        "Cake",
        "Dream",
        "Tidiness",
        "sleep",
        "Being Happy",
        "Age",
        "Voice",
        "Indoor Games",
        "Time Management",
        "Name",
        "Meeting New People",
        "discussion",
        "Singing ",
        "Birthdays",
        "History",
        "Shoes",
        "Gifts",
        "Perfume",
        "Insects",
        "Running",
        "Being Bored",
        "Hats",
        "Photography",
        "Colors",
        "Concentration",
        "Hand Writing",
        "Relatives",
        "Computer",
        "science class",
        "Farming ",
        "Music",
        "Patience",
        "Sunglasses",
        "Dance",
        "Smile",
        "scenery",
        "Space Travel",
        "Family",
        "Drinking Water",
        "Foreign Food",
        "Being in a Hurry",
        "Forget Things",
        "Plan",
        "Recycle ",
        "celebrity",
        "Jokes and Comedies ",
        "Walking",
        "pen & pencil ",
        "Plants",
        "Maps",
        "Museums",
        "Friends",
        "Text Messaging",
        "City Life",
        "Jeans",
        "Sport ",
        "List ",
        "Chocolate",
        "Picnic ",
        "water sports",
        "Art",
        "Fishing",
        "Bags",
        "Books",
        "Outdoor Activity",
        "Birds",
        "Boats",
    )
    val holderList2 = mutableListOf(
        "Describe  your  favorite  movie ",
        "Describe a time  you  got  lost  in  a  place  you  didn't  know about",
        "Describe your first day at school ",
        "Describe  a  live  sports  match  that  you  have  watched",
        "Describe  an  article  on  health  you  read  in  a  magazine  or  on  the  internet",
        "Describe a  street  market  in  your  city",
        "Describe  an  argument  two  of  your  friends  had?",
        "Describe  a  natural  talent  you  want  to  improve  like  sports  music",
        "Describe  an  occasion  when  you  were  not  allowed  to  use  your  mobile  phone",
        "Describe  a  piece  of  local  news  that  people  are  interested  in",
        "Describe  a  tall  building  in  your  city  you  like  or  dislike",
        "Describe  an  occasion  when  many  people  were  smiling",
        "Describe  a  time  you  saw  something  interesting  on  social  media",
        "Describe  a  law  on  environmental  protection ",
        "Describe  a  town  or  city  where  you  would  like  to  live  in  the  future",
        "Describe  a  puzzle  (jigsaw,  crossword,  etc)  you  have  played",
        "Describe  a  plan  in  your  life  that  is  not  related  to  work  or  study",
        "Describe  an  art  or  craft  activity  (e.g  painting,  woodwork,  etc)  that  you  had  (at  school)",
        "Describe  a  company  where  you  live  that  employs  a  lot  of  people  ",
        "Describe  a  quiet  place  you  like  to  spend  your  time  in",
        "Describe an aquatic animal",
        "Describe a bag you want to own",
        "Describe  a  time  when  you  helped  a  friend",
        "Describe  a  leisure  activity  near/on  the  sea  that  you  want  to  try",
        "Describe  a  time  when  you  shared  something  with  others  (or  another  person)",
        "Describe a goal you want to achieve in the future or Describe an ambition that you have had for a long time",
        "Talk  about  a  toy  you  liked  in  your  childhood.",
        "Describe  a  tradition  in  your  country128",
        "Describe  a  person  who  you  think  is  very  open 131",
        "Describe  a  time  you  saw  children  behave  badly  in  public",
        "Describe  a  time  when  you  first  talked  in  a  foreign  language",
        "Describe  an  old  person  you  know  and  respect",
        "Describe your favorite singer ",
        "Describe a time you made a promise to someone",
        "Describe tan art exhibition that you visited",
        "Describe a time when you told your friend an important truth",
        "Describe a special hotel you stayed in",
        "Describe a person who wears unusual clothes",
        "Describe a place(/person/home) you like to visit but you don’t want to live there?",
        "Describe a perfect job you would like to have in the future",
        "Describe a skill that you can teach other people ",
        "Describe a time when you needed to use your imagination",
        "Describe a part of a city or a town you enjoy spending time in",
        "Describe a famous person that you are interested in",
        "Describe a time when your computer broke down:",
        "Describe a polite person whom you know",
        "Describe a time when you encouraged someone to do someone to do something that  he/she didn’t want to do",
        "Describe a decision made by others/someone that you disagreed with",
        "Describe a time when you felt bored",
        "Describe the time when you had to sing a song or a poem in front of public",
        "Describe a piece of international news that you have recently heard",
        "Describe a time when you had to wait in a long line",
        "Describe a short trip that you often take but you do not like",
        "Describe  a  time  when  you  changed  your  opinion",
        "Describe  a  person  who  helps  others  in  his  or  her  spare  time ",
        "Describe  a  film/movie  that  made  you  laugh",
        "Describe an interesting conversation that you had",
        "Describe an unforgettable bike(bicycle) trip",
        "Describe a computer/phone game you enjoy playing since your childhood",
        "Describe a time when you were really close to a wild animal",
        "Describe your favourite weather",
        "Describe a thing you bought and you are happy about",
        "Talk about a time when you gave advice to someone.",
        "Describe something important that has been kept in your family for a long time ",
        "Describe an occasion when you ate a kind of food for first time ",
        "Describe  an  old  friend  you  got  in  contact  with  again",
        "Describe  a  family  which  you  like  and  are  happy  to  know"
    )
    val holderList3 = mutableListOf(
        "Speaking Material By IDP\n https://www.idpielts.me/speaking-practice-test/",
        "IELTS Material By LIZ.\n https://ieltsliz.com/ielts-speaking-free-lessons-essential-tips/",
        "Makkar IELTS Material(Paid)\n https://makkarielts.com/",
        "IELTS Advantage\n https://www.ieltsadvantage.com/ielts-speaking/",
        "Fastrack IELTS(Youtube)\n https://youtube.com/playlist?list=PLGHMg8AQ02x1ErPUMjxa9De0OBnzoSfmk",
        "Academic English Help(Youtube)\n https://www.youtube.com/watch?v=2xZoXIaqtVY&list=PL4BA6C1AD8454AF76"
    )
    val part1Speech = mutableListOf(
        "Hello dear , I am Prime A I and your speaking examiner. This IELTS Test is divided into three parts. Let's start with Introduction and some Basic Questions. \nWhat is Your Full Name",
        "\nWhere are You Come From",
        "\nAre You A Student or A Worker",
        "\nAre you Live in Village or in City"
    )
    val part2Speech =
        mutableListOf("Let's continue with cue card questions. Your topic is shown in text box. You have 1 minute for prepare your answers and you will be given 2 to 3 minutes for your speaking part.Your 1 minute preparation time start now.")
    val part3Speech =
        mutableListOf("Let's start follow up questions related to your part 2 cue card topic. Please try to elaborate your answers")

}